CREATE DATABASE SalonTPS;
USE SalonTPS;

CREATE TABLE ACCOUNT (
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    phone INT NOT NULL UNIQUE,
    password VARCHAR (20) NOT NULL,
    name VARCHAR (50) NOT NULL,
    role VARCHAR (10) NOT NULL
);

CREATE TABLE SERVICE (
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    name VARCHAR(20) NOT NULL UNIQUE,
    price FLOAT NOT NULL
);

CREATE TABLE BOOKING (
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    service_id INT NOT NULL,
    account_id INT NOT NULL,
    date Date,

    FOREIGN KEY(service_id) REFERENCES SERVICE(id),
    FOREIGN KEY(account_id) REFERENCES ACCOUNT(id)
);